package org.sid.entite ;
// Generated 20 sept. 2017 20:45:31 by Hibernate Tools 4.3.1



/**
 * Absence generated by hbm2java
 */
public class Absence  implements java.io.Serializable {


     private AbsenceId id;
     private Cours cours;
     private Etudiant etudiant;
     private String type;

    public Absence() {
    }

	
    public Absence(AbsenceId id, Cours cours, Etudiant etudiant) {
        this.id = id;
        this.cours = cours;
        this.etudiant = etudiant;
    }
    public Absence(AbsenceId id, Cours cours, Etudiant etudiant, String type) {
       this.id = id;
       this.cours = cours;
       this.etudiant = etudiant;
       this.type = type;
    }
    
    
    public void init(){
    	System.out.println("Initialisation");
    }
   
   
    public AbsenceId getId() {
        return this.id;
    }
    
    public void setId(AbsenceId id) {
        this.id = id;
    }
    public Cours getCours() {
        return this.cours;
    }
    
    public void setCours(Cours cours) {
        this.cours = cours;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


