package org.sid.entite ;
// Generated 20 sept. 2017 20:45:31 by Hibernate Tools 4.3.1



/**
 * AbsenceId generated by hbm2java
 */
public class AbsenceId  implements java.io.Serializable {


     private String codeutilisateur;
     private String codecours;

    public AbsenceId() {
    }

    public AbsenceId(String codeutilisateur, String codecours) {
       this.codeutilisateur = codeutilisateur;
       this.codecours = codecours;
    }
   
    public String getCodeutilisateur() {
        return this.codeutilisateur;
    }
    
    public void setCodeutilisateur(String codeutilisateur) {
        this.codeutilisateur = codeutilisateur;
    }
    public String getCodecours() {
        return this.codecours;
    }
    
    public void setCodecours(String codecours) {
        this.codecours = codecours;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbsenceId) ) return false;
		 AbsenceId castOther = ( AbsenceId ) other; 
         
		 return ( (this.getCodeutilisateur()==castOther.getCodeutilisateur()) || ( this.getCodeutilisateur()!=null && castOther.getCodeutilisateur()!=null && this.getCodeutilisateur().equals(castOther.getCodeutilisateur()) ) )
 && ( (this.getCodecours()==castOther.getCodecours()) || ( this.getCodecours()!=null && castOther.getCodecours()!=null && this.getCodecours().equals(castOther.getCodecours()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeutilisateur() == null ? 0 : this.getCodeutilisateur().hashCode() );
         result = 37 * result + ( getCodecours() == null ? 0 : this.getCodecours().hashCode() );
         return result;
   }   


}


