package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Classe generated by hbm2java
 */
public class Classe  implements java.io.Serializable {


     private String codeclasse;
     private Filiere filiere;
     private Niveau niveau;
     private String lbelleClasse;
     private Integer nombreeEtudiant;
     private String type;
     private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);
     private Set<Maquette> maquettes = new HashSet<Maquette>(0);
     private Set<EmploisDuTemps> emploisDuTempses = new HashSet<EmploisDuTemps>(0);

    public Classe() {
    }

	
    public Classe(String codeclasse, Filiere filiere, Niveau niveau) {
        this.codeclasse = codeclasse;
        this.filiere = filiere;
        this.niveau = niveau;
    }
    public Classe(String codeclasse, Filiere filiere, Niveau niveau, String lbelleClasse, Integer nombreeEtudiant, String type, Set<Etudiant> etudiants, Set<Maquette> maquettes, Set<EmploisDuTemps> emploisDuTempses) {
       this.codeclasse = codeclasse;
       this.filiere = filiere;
       this.niveau = niveau;
       this.lbelleClasse = lbelleClasse;
       this.nombreeEtudiant = nombreeEtudiant;
       this.type = type;
       this.etudiants = etudiants;
       this.maquettes = maquettes;
       this.emploisDuTempses = emploisDuTempses;
    }
   
    public String getCodeclasse() {
        return this.codeclasse;
    }
    
    public void setCodeclasse(String codeclasse) {
        this.codeclasse = codeclasse;
    }
    public Filiere getFiliere() {
        return this.filiere;
    }
    
    public void setFiliere(Filiere filiere) {
        this.filiere = filiere;
    }
    public Niveau getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Niveau niveau) {
        this.niveau = niveau;
    }
    public String getLbelleClasse() {
        return this.lbelleClasse;
    }
    
    public void setLbelleClasse(String lbelleClasse) {
        this.lbelleClasse = lbelleClasse;
    }
    public Integer getNombreeEtudiant() {
        return this.nombreeEtudiant;
    }
    
    public void setNombreeEtudiant(Integer nombreeEtudiant) {
        this.nombreeEtudiant = nombreeEtudiant;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<Etudiant> getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set<Etudiant> etudiants) {
        this.etudiants = etudiants;
    }
    public Set<Maquette> getMaquettes() {
        return this.maquettes;
    }
    
    public void setMaquettes(Set<Maquette> maquettes) {
        this.maquettes = maquettes;
    }
    public Set<EmploisDuTemps> getEmploisDuTempses() {
        return this.emploisDuTempses;
    }
    
    public void setEmploisDuTempses(Set<EmploisDuTemps> emploisDuTempses) {
        this.emploisDuTempses = emploisDuTempses;
    }




}


