package org.sid.entite ;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours  implements java.io.Serializable {


     private String codecours;
     private Ec ec;
     private Enseignant enseignant;
     private Date date;
     private String heureDebut;
     private String heureFin;
     private Set<Absence> absences = new HashSet<Absence>(0);

    public Cours() {
    }

	
    public Cours(String codecours, Ec ec, Enseignant enseignant) {
        this.codecours = codecours;
        this.ec = ec;
        this.enseignant = enseignant;
    }
    public Cours(String codecours, Ec ec, Enseignant enseignant, Date date, String heureDebut, String heureFin, Set<Absence> absences) {
       this.codecours = codecours;
       this.ec = ec;
       this.enseignant = enseignant;
       this.date = date;
       this.heureDebut = heureDebut;
       this.heureFin = heureFin;
       this.absences = absences;
    }
   
    public String getCodecours() {
        return this.codecours;
    }
    
    public void setCodecours(String codecours) {
        this.codecours = codecours;
    }
    public Ec getEc() {
        return this.ec;
    }
    
    public void setEc(Ec ec) {
        this.ec = ec;
    }
    public Enseignant getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getHeureDebut() {
        return this.heureDebut;
    }
    
    public void setHeureDebut(String heureDebut) {
        this.heureDebut = heureDebut;
    }
    public String getHeureFin() {
        return this.heureFin;
    }
    
    public void setHeureFin(String heureFin) {
        this.heureFin = heureFin;
    }
    public Set<Absence> getAbsences() {
        return this.absences;
    }
    
    public void setAbsences(Set<Absence> absences) {
        this.absences = absences;
    }




}


