package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Domaine generated by hbm2java
 */
public class Domaine  implements java.io.Serializable {


     private String codedomaine;
     private Etablissement etablissement;
     private String nomDomaine;
     private Set<Filiere> filieres = new HashSet<Filiere>(0);

    public Domaine() {
    }

	
    public Domaine(String codedomaine, Etablissement etablissement) {
        this.codedomaine = codedomaine;
        this.etablissement = etablissement;
    }
    public Domaine(String codedomaine, Etablissement etablissement, String nomDomaine, Set<Filiere> filieres) {
       this.codedomaine = codedomaine;
       this.etablissement = etablissement;
       this.nomDomaine = nomDomaine;
       this.filieres = filieres;
    }
   
    public String getCodedomaine() {
        return this.codedomaine;
    }
    
    public void setCodedomaine(String codedomaine) {
        this.codedomaine = codedomaine;
    }
    public Etablissement getEtablissement() {
        return this.etablissement;
    }
    
    public void setEtablissement(Etablissement etablissement) {
        this.etablissement = etablissement;
    }
    public String getNomDomaine() {
        return this.nomDomaine;
    }
    
    public void setNomDomaine(String nomDomaine) {
        this.nomDomaine = nomDomaine;
    }
    public Set<Filiere> getFilieres() {
        return this.filieres;
    }
    
    public void setFilieres(Set<Filiere> filieres) {
        this.filieres = filieres;
    }




}


