package org.sid.entite ;


import java.util.Date;

/**
 * Dossier generated by hbm2java
 */
public class Dossier  implements java.io.Serializable {


     private String codedossier;
     private Etudiant etudiant;
     private Secretaire secretaire;
     private Date dateCreation;
     private String url;

    public Dossier() {
    }

	
    public Dossier(String codedossier, Etudiant etudiant, Secretaire secretaire) {
        this.codedossier = codedossier;
        this.etudiant = etudiant;
        this.secretaire = secretaire;
    }
    public Dossier(String codedossier, Etudiant etudiant, Secretaire secretaire, Date dateCreation, String url) {
       this.codedossier = codedossier;
       this.etudiant = etudiant;
       this.secretaire = secretaire;
       this.dateCreation = dateCreation;
       this.url = url;
    }
   
    public String getCodedossier() {
        return this.codedossier;
    }
    
    public void setCodedossier(String codedossier) {
        this.codedossier = codedossier;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public Secretaire getSecretaire() {
        return this.secretaire;
    }
    
    public void setSecretaire(Secretaire secretaire) {
        this.secretaire = secretaire;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


