package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Ec generated by hbm2java
 */
public class Ec  implements java.io.Serializable {


     private String codematiere;
     private Ue ue;
     private String libelleMatiere;
     private String quantumhoraire;
     private Integer credit;
     private String tp;
     private String td;
     private String tpe;
     private String coursmagistraux;
     private Set<Evaluer> evaluers = new HashSet<Evaluer>(0);
     private Set<Cours> courses = new HashSet<Cours>(0);

    public Ec() {
    }

	
    public Ec(String codematiere, Ue ue) {
        this.codematiere = codematiere;
        this.ue = ue;
    }
    public Ec(String codematiere, Ue ue, String libelleMatiere, String quantumhoraire, Integer credit, String tp, String td, String tpe, String coursmagistraux, Set<Evaluer> evaluers, Set<Cours> courses) {
       this.codematiere = codematiere;
       this.ue = ue;
       this.libelleMatiere = libelleMatiere;
       this.quantumhoraire = quantumhoraire;
       this.credit = credit;
       this.tp = tp;
       this.td = td;
       this.tpe = tpe;
       this.coursmagistraux = coursmagistraux;
       this.evaluers = evaluers;
       this.courses = courses;
    }
   
    public String getCodematiere() {
        return this.codematiere;
    }
    
    public void setCodematiere(String codematiere) {
        this.codematiere = codematiere;
    }
    public Ue getUe() {
        return this.ue;
    }
    
    public void setUe(Ue ue) {
        this.ue = ue;
    }
    public String getLibelleMatiere() {
        return this.libelleMatiere;
    }
    
    public void setLibelleMatiere(String libelleMatiere) {
        this.libelleMatiere = libelleMatiere;
    }
    public String getQuantumhoraire() {
        return this.quantumhoraire;
    }
    
    public void setQuantumhoraire(String quantumhoraire) {
        this.quantumhoraire = quantumhoraire;
    }
    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }
    public String getTp() {
        return this.tp;
    }
    
    public void setTp(String tp) {
        this.tp = tp;
    }
    public String getTd() {
        return this.td;
    }
    
    public void setTd(String td) {
        this.td = td;
    }
    public String getTpe() {
        return this.tpe;
    }
    
    public void setTpe(String tpe) {
        this.tpe = tpe;
    }
    public String getCoursmagistraux() {
        return this.coursmagistraux;
    }
    
    public void setCoursmagistraux(String coursmagistraux) {
        this.coursmagistraux = coursmagistraux;
    }
    public Set<Evaluer> getEvaluers() {
        return this.evaluers;
    }
    
    public void setEvaluers(Set<Evaluer> evaluers) {
        this.evaluers = evaluers;
    }
    public Set<Cours> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Cours> courses) {
        this.courses = courses;
    }




}


