package org.sid.entite ;



/**
 * EmploisDuTemps generated by hbm2java
 */
public class EmploisDuTemps  implements java.io.Serializable {


     private String codeEmploisdutemps;
     private Classe classe;
     private Responsable responsable;
     private Semestre semestre;
     private String datedebut;
     private String datefin;

    public EmploisDuTemps() {
    }

	
    public EmploisDuTemps(String codeEmploisdutemps, Classe classe, Responsable responsable, Semestre semestre) {
        this.codeEmploisdutemps = codeEmploisdutemps;
        this.classe = classe;
        this.responsable = responsable;
        this.semestre = semestre;
    }
    public EmploisDuTemps(String codeEmploisdutemps, Classe classe, Responsable responsable, Semestre semestre, String datedebut, String datefin) {
       this.codeEmploisdutemps = codeEmploisdutemps;
       this.classe = classe;
       this.responsable = responsable;
       this.semestre = semestre;
       this.datedebut = datedebut;
       this.datefin = datefin;
    }
   
    public String getCodeEmploisdutemps() {
        return this.codeEmploisdutemps;
    }
    
    public void setCodeEmploisdutemps(String codeEmploisdutemps) {
        this.codeEmploisdutemps = codeEmploisdutemps;
    }
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }
    public Responsable getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(Responsable responsable) {
        this.responsable = responsable;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
    public String getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(String datedebut) {
        this.datedebut = datedebut;
    }
    public String getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(String datefin) {
        this.datefin = datefin;
    }




}


