package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * EnseignantResponsable generated by hbm2java
 */
public class EnseignantResponsable  implements java.io.Serializable {


     private String codeutilisateur;
     private Enseignant enseignant;
     private Set<Filiere> filieres = new HashSet<Filiere>(0);

    public EnseignantResponsable() {
    }

	
    public EnseignantResponsable(Enseignant enseignant) {
        this.enseignant = enseignant;
    }
    public EnseignantResponsable(Enseignant enseignant, Set<Filiere> filieres) {
       this.enseignant = enseignant;
       this.filieres = filieres;
    }
   
    public String getCodeutilisateur() {
        return this.codeutilisateur;
    }
    
    public void setCodeutilisateur(String codeutilisateur) {
        this.codeutilisateur = codeutilisateur;
    }
    public Enseignant getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }
    public Set<Filiere> getFilieres() {
        return this.filieres;
    }
    
    public void setFilieres(Set<Filiere> filieres) {
        this.filieres = filieres;
    }




}


