package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Etablissement generated by hbm2java
 */
public class Etablissement  implements java.io.Serializable {


     private String codeetablissement;
     private Responsable responsable;
     private String libelleEtablissemant;
     private Set<Domaine> domaines = new HashSet<Domaine>(0);

    public Etablissement() {
    }

	
    public Etablissement(String codeetablissement, Responsable responsable) {
        this.codeetablissement = codeetablissement;
        this.responsable = responsable;
    }
    public Etablissement(String codeetablissement, Responsable responsable, String libelleEtablissemant, Set<Domaine> domaines) {
       this.codeetablissement = codeetablissement;
       this.responsable = responsable;
       this.libelleEtablissemant = libelleEtablissemant;
       this.domaines = domaines;
    }
   
    public String getCodeetablissement() {
        return this.codeetablissement;
    }
    
    public void setCodeetablissement(String codeetablissement) {
        this.codeetablissement = codeetablissement;
    }
    public Responsable getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(Responsable responsable) {
        this.responsable = responsable;
    }
    public String getLibelleEtablissemant() {
        return this.libelleEtablissemant;
    }
    
    public void setLibelleEtablissemant(String libelleEtablissemant) {
        this.libelleEtablissemant = libelleEtablissemant;
    }
    public Set<Domaine> getDomaines() {
        return this.domaines;
    }
    
    public void setDomaines(Set<Domaine> domaines) {
        this.domaines = domaines;
    }




}


