package org.sid.entite ;



/**
 * EvaluerId generated by hbm2java
 */
public class EvaluerId  implements java.io.Serializable {


     private String codeutilisateur;
     private String codematiere;

    public EvaluerId() {
    }

    public EvaluerId(String codeutilisateur, String codematiere) {
       this.codeutilisateur = codeutilisateur;
       this.codematiere = codematiere;
    }
   
    public String getCodeutilisateur() {
        return this.codeutilisateur;
    }
    
    public void setCodeutilisateur(String codeutilisateur) {
        this.codeutilisateur = codeutilisateur;
    }
    public String getCodematiere() {
        return this.codematiere;
    }
    
    public void setCodematiere(String codematiere) {
        this.codematiere = codematiere;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluerId) ) return false;
		 EvaluerId castOther = ( EvaluerId ) other; 
         
		 return ( (this.getCodeutilisateur()==castOther.getCodeutilisateur()) || ( this.getCodeutilisateur()!=null && castOther.getCodeutilisateur()!=null && this.getCodeutilisateur().equals(castOther.getCodeutilisateur()) ) )
 && ( (this.getCodematiere()==castOther.getCodematiere()) || ( this.getCodematiere()!=null && castOther.getCodematiere()!=null && this.getCodematiere().equals(castOther.getCodematiere()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeutilisateur() == null ? 0 : this.getCodeutilisateur().hashCode() );
         result = 37 * result + ( getCodematiere() == null ? 0 : this.getCodematiere().hashCode() );
         return result;
   }   


}


