package org.sid.entite ;


import java.math.BigDecimal;
import java.util.Date;

/**
 * Evaluer generated by hbm2java
 */
public class Evaluer  implements java.io.Serializable {


     private EvaluerId id;
     private Ec ec;
     private Etudiant etudiant;
     private Date dateEvaluation;
     private BigDecimal note;

    public Evaluer() {
    }

	
    public Evaluer(EvaluerId id, Ec ec, Etudiant etudiant) {
        this.id = id;
        this.ec = ec;
        this.etudiant = etudiant;
    }
    public Evaluer(EvaluerId id, Ec ec, Etudiant etudiant, Date dateEvaluation, BigDecimal note) {
       this.id = id;
       this.ec = ec;
       this.etudiant = etudiant;
       this.dateEvaluation = dateEvaluation;
       this.note = note;
    }
   
    public EvaluerId getId() {
        return this.id;
    }
    
    public void setId(EvaluerId id) {
        this.id = id;
    }
    public Ec getEc() {
        return this.ec;
    }
    
    public void setEc(Ec ec) {
        this.ec = ec;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public Date getDateEvaluation() {
        return this.dateEvaluation;
    }
    
    public void setDateEvaluation(Date dateEvaluation) {
        this.dateEvaluation = dateEvaluation;
    }
    public BigDecimal getNote() {
        return this.note;
    }
    
    public void setNote(BigDecimal note) {
        this.note = note;
    }




}


