package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Filiere generated by hbm2java
 */
public class Filiere  implements java.io.Serializable {


     private String codefiliere;
     private Domaine domaine;
     private EnseignantResponsable enseignantResponsable;
     private String libelleFiliere;
     private Set<Classe> classes = new HashSet<Classe>(0);

    public Filiere() {
    }

	
    public Filiere(String codefiliere, Domaine domaine, EnseignantResponsable enseignantResponsable) {
        this.codefiliere = codefiliere;
        this.domaine = domaine;
        this.enseignantResponsable = enseignantResponsable;
    }
    public Filiere(String codefiliere, Domaine domaine, EnseignantResponsable enseignantResponsable, String libelleFiliere, Set<Classe> classes) {
       this.codefiliere = codefiliere;
       this.domaine = domaine;
       this.enseignantResponsable = enseignantResponsable;
       this.libelleFiliere = libelleFiliere;
       this.classes = classes;
    }
   
    public String getCodefiliere() {
        return this.codefiliere;
    }
    
    public void setCodefiliere(String codefiliere) {
        this.codefiliere = codefiliere;
    }
    public Domaine getDomaine() {
        return this.domaine;
    }
    
    public void setDomaine(Domaine domaine) {
        this.domaine = domaine;
    }
    public EnseignantResponsable getEnseignantResponsable() {
        return this.enseignantResponsable;
    }
    
    public void setEnseignantResponsable(EnseignantResponsable enseignantResponsable) {
        this.enseignantResponsable = enseignantResponsable;
    }
    public String getLibelleFiliere() {
        return this.libelleFiliere;
    }
    
    public void setLibelleFiliere(String libelleFiliere) {
        this.libelleFiliere = libelleFiliere;
    }
    public Set<Classe> getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set<Classe> classes) {
        this.classes = classes;
    }




}


