package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Maquette generated by hbm2java
 */
public class Maquette  implements java.io.Serializable {


     private String codemaquette;
     private Classe classe;
     private String annee;
     private Set<Semestre> semestres = new HashSet<Semestre>(0);

    public Maquette() {
    }

	
    public Maquette(String codemaquette, Classe classe) {
        this.codemaquette = codemaquette;
        this.classe = classe;
    }
    public Maquette(String codemaquette, Classe classe, String annee, Set<Semestre> semestres) {
       this.codemaquette = codemaquette;
       this.classe = classe;
       this.annee = annee;
       this.semestres = semestres;
    }
   
    public String getCodemaquette() {
        return this.codemaquette;
    }
    
    public void setCodemaquette(String codemaquette) {
        this.codemaquette = codemaquette;
    }
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }
    public Set<Semestre> getSemestres() {
        return this.semestres;
    }
    
    public void setSemestres(Set<Semestre> semestres) {
        this.semestres = semestres;
    }




}


