package org.sid.entite ;

import java.util.HashSet;
import java.util.Set;

/**
 * Niveau generated by hbm2java
 */
public class Niveau  implements java.io.Serializable {


     private int idniveau;
     private String libelle;
     private Set<Classe> classes = new HashSet<Classe>(0);

    public Niveau() {
    }

	
    public Niveau(int idniveau) {
        this.idniveau = idniveau;
    }
    public Niveau(int idniveau, String libelle, Set<Classe> classes) {
       this.idniveau = idniveau;
       this.libelle = libelle;
       this.classes = classes;
    }
   
   
    public int getIdniveau() {
        return this.idniveau;
    }
    
    public void setIdniveau(int idniveau) {
        this.idniveau = idniveau;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        
        this.libelle = libelle;
    }
    public Set<Classe> getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set<Classe> classes) {
        this.classes = classes;
    }




}


