package org.sid.entite ;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paiement generated by hbm2java
 */
public class Paiement  implements java.io.Serializable {


     private String codepaiement;
     private Etudiant etudiant;
     private double montant ;
     private int nbmois ;
     private String couverture;
     private String scolarite;
     private String typedepaiement;
     private Date datePaiement;
     private String annee;
     private Set<Facture> factures = new HashSet<Facture>(0);

    public int getNbmois() {
        return nbmois;
    }

    public void setNbmois(int nbmois) {
        this.nbmois = nbmois;
    }

    public Paiement() {
    }

	
    public Paiement(String codepaiement) {
        this.codepaiement = codepaiement;
        
    }
    public Paiement(String codepaiement, Etudiant etudiant, String couverture, String scolarite, String typedepaiement, Date datePaiement, String annee, Set<Facture> factures) {
       this.codepaiement = codepaiement;
       this.etudiant = etudiant;
       
       this.couverture = couverture;
       this.scolarite = scolarite;
       this.typedepaiement = typedepaiement;
       this.datePaiement = datePaiement;
       this.annee = annee;
       this.factures = factures;
    }
   
    public String getCodepaiement() {
        return this.codepaiement;
    }
    
    public void setCodepaiement(String codepaiement) {
        this.codepaiement = codepaiement;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    
    public String getCouverture() {
        return this.couverture;
    }
    
    public void setCouverture(String couverture) {
        this.couverture = couverture;
    }
    public String getScolarite() {
        return this.scolarite;
    }
    
    public void setScolarite(String scolarite) {
        this.scolarite = scolarite;
    }
    public String getTypedepaiement() {
        return this.typedepaiement;
    }
    
    public void setTypedepaiement(String typedepaiement) {
        this.typedepaiement = typedepaiement;
    }
    public Date getDatePaiement() {
        return this.datePaiement;
    }
    
    public void setDatePaiement(Date datePaiement) {
        this.datePaiement = datePaiement;
    }
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }
    public Set<Facture> getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set<Facture> factures) {
        this.factures = factures;
    }

    public double getMontant() {
        return montant;
    }

    public void setMontant(double montant) {
        this.montant = montant;
    }

    public int getNb_mois() {
        return nbmois;
    }

    public void setNb_mois(int nb_mois) {
        this.nbmois = nb_mois;
    }




}


