package org.sid.entite ;

import java.util.HashSet;
import java.util.Set;

/**
 * Responsable generated by hbm2java
 */
public class Responsable  implements java.io.Serializable {


     private String codeutilisateur;
     private Utilisateur utilisateur;
     private Set<Etablissement> etablissements = new HashSet<Etablissement>(0);
     private Set<EmploisDuTemps> emploisDuTempses = new HashSet<EmploisDuTemps>(0);

    public Responsable() {
    }

	
    public Responsable(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Responsable(Utilisateur utilisateur, Set<Etablissement> etablissements, Set<EmploisDuTemps> emploisDuTempses) {
       this.utilisateur = utilisateur;
       this.etablissements = etablissements;
       this.emploisDuTempses = emploisDuTempses;
    }
   
    public String getCodeutilisateur() {
        return this.codeutilisateur;
    }
    
    public void setCodeutilisateur(String codeutilisateur) {
        this.codeutilisateur = codeutilisateur;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Set<Etablissement> getEtablissements() {
        return this.etablissements;
    }
    
    public void setEtablissements(Set<Etablissement> etablissements) {
        this.etablissements = etablissements;
    }
    public Set<EmploisDuTemps> getEmploisDuTempses() {
        return this.emploisDuTempses;
    }
    
    public void setEmploisDuTempses(Set<EmploisDuTemps> emploisDuTempses) {
        this.emploisDuTempses = emploisDuTempses;
    }




}


