package org.sid.entite ;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Semestre generated by hbm2java
 */
public class Semestre  implements java.io.Serializable {


     private String codesemestre;
     private Maquette maquette;
     private String libelleSemestre;
     private Date dateDebut;
     private Date dateFin;
     private Set<EmploisDuTemps> emploisDuTempses = new HashSet<EmploisDuTemps>(0);
     private Set<Ue> ues = new HashSet<Ue>(0);

    public Semestre() {
    }

	
    public Semestre(String codesemestre, Maquette maquette) {
        this.codesemestre = codesemestre;
        this.maquette = maquette;
    }
    public Semestre(String codesemestre, Maquette maquette, String libelleSemestre, Date dateDebut, Date dateFin, Set<EmploisDuTemps> emploisDuTempses, Set<Ue> ues) {
       this.codesemestre = codesemestre;
       this.maquette = maquette;
       this.libelleSemestre = libelleSemestre;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.emploisDuTempses = emploisDuTempses;
       this.ues = ues;
    }
   
    public String getCodesemestre() {
        return this.codesemestre;
    }
    
    public void setCodesemestre(String codesemestre) {
        this.codesemestre = codesemestre;
    }
    public Maquette getMaquette() {
        return this.maquette;
    }
    
    public void setMaquette(Maquette maquette) {
        this.maquette = maquette;
    }
    public String getLibelleSemestre() {
        return this.libelleSemestre;
    }
    
    public void setLibelleSemestre(String libelleSemestre) {
        this.libelleSemestre = libelleSemestre;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public Set<EmploisDuTemps> getEmploisDuTempses() {
        return this.emploisDuTempses;
    }
    
    public void setEmploisDuTempses(Set<EmploisDuTemps> emploisDuTempses) {
        this.emploisDuTempses = emploisDuTempses;
    }
    public Set<Ue> getUes() {
        return this.ues;
    }
    
    public void setUes(Set<Ue> ues) {
        this.ues = ues;
    }




}


