package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Ue generated by hbm2java
 */
public class Ue  implements java.io.Serializable {


     private String codeue;
     private Semestre semestre;
     private String libelle;
     private Integer credit;
     private Set<Ec> ecs = new HashSet<Ec>(0);

    public Ue() {
    }

	
    public Ue(String codeue, Semestre semestre) {
        this.codeue = codeue;
        this.semestre = semestre;
    }
    public Ue(String codeue, Semestre semestre, String libelle, Integer credit, Set<Ec> ecs) {
       this.codeue = codeue;
       this.semestre = semestre;
       this.libelle = libelle;
       this.credit = credit;
       this.ecs = ecs;
    }
   
    public String getCodeue() {
        return this.codeue;
    }
    
    public void setCodeue(String codeue) {
        this.codeue = codeue;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }
    public Set<Ec> getEcs() {
        return this.ecs;
    }
    
    public void setEcs(Set<Ec> ecs) {
        this.ecs = ecs;
    }




}


