package org.sid.entite ;


import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private String codeutilisateur;
     private String nom;
     private String prenom;
     private String datedenaissance;
     private String lieudenaissance ;
     private String telephone;
     private String adresse;
     private String nationalite;
     private String email;
     private String login;
     private String password;
     private Etudiant etudiant;
     private Set<Message> messages = new HashSet<>(0);
     private Responsable responsable;
     private Administrateur administrateur;
     private Secretaire secretaire;
     private Comptable comptable;
     private Enseignant enseignant;
     private String sms,selection;
     
     
     
     
      
    public void init(){
         System.out.println("Abou Sow");
     }
     
     
     

    public String getSms() {
        return sms;
    }

    public void setSms(String sms) {
        this.sms = sms;
       // System.out.println("Abou sow 80");
    }

    public String getSelection() {
        return selection;
    }

    public void setSelection(String selection) {
        this.selection = selection;
    }

    public Utilisateur() {
    }

	
    public Utilisateur(String codeutilisateur) {
        this.codeutilisateur = codeutilisateur;
    }
    
    
    
    
    public Utilisateur(String codeutilisateur, String nom, String prenom, String datedenaissance,String telephone, String adresse, String ville, String pays, String email, Integer boitePostale, String cin, String login, String password, Etudiant etudiant, Set<Message> messages, Responsable responsable, Administrateur administrateur, Secretaire secretaire, Comptable comptable, Enseignant enseignant) {
       this.codeutilisateur = codeutilisateur;
       this.nom = nom;
       this.prenom = prenom;
       this.datedenaissance = datedenaissance;
      
       this.telephone = telephone;
       this.adresse = adresse;
      
       
       this.email = email;
       
       
       this.login = login;
       this.password = password;
       this.etudiant = etudiant;
       this.messages = messages;
       this.responsable = responsable;
       this.administrateur = administrateur;
       this.secretaire = secretaire;
       this.comptable = comptable;
       this.enseignant = enseignant;
    }

    public Utilisateur(String codeutilisateur, String nom, String prenom,String situaionM, String telephone, String adresse, String ville, String pays, String email, String cin, String login, String password) {
        this.codeutilisateur = codeutilisateur;
        this.nom = nom;
        this.prenom = prenom;
        
        this.telephone = telephone;
        this.adresse = adresse;
        
        
        this.email = email;
        
        this.login = login;
        this.password = password;
        
    }

    public Utilisateur(String codeutilisateur, String nom, String prenom, String datedenaissance, String lieudenaissance, String telephone, String adresse, String nationalite, String email) {
        this.codeutilisateur = codeutilisateur;
        this.nom = nom;
        this.prenom = prenom;
        this.datedenaissance = datedenaissance;
        this.lieudenaissance = lieudenaissance;
        this.telephone = telephone;
        this.adresse = adresse;
        this.nationalite = nationalite;
        this.email = email;
    }
    
  

    public Utilisateur(String codeutilisateur, String nom, String prenom, String datedenaissance, String lieudenaissance, String telephone, String adresse, String nationalite, String email, String login, String password, String sms, String selection) {
        this.codeutilisateur = codeutilisateur;
        this.nom = nom;
        this.prenom = prenom;
        this.datedenaissance = datedenaissance;
        this.lieudenaissance = lieudenaissance;
        this.telephone = telephone;
        this.adresse = adresse;
        this.nationalite = nationalite;
        this.email = email;
        this.login = login;
        this.password = password;
        this.sms = sms;
        this.selection = selection;
    }
    
    
    
    
   
    public String getCodeutilisateur() {
        return this.codeutilisateur;
    }
    
    public void setCodeutilisateur(String codeutilisateur) {
        this.codeutilisateur = codeutilisateur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getDatedenaissance() {
        return this.datedenaissance;
    }
    
    public void setDatedenaissance(String datedenaissance) {
        this.datedenaissance = datedenaissance;
    }
  
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
  
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }
    public Responsable getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(Responsable responsable) {
        this.responsable = responsable;
    }
    public Administrateur getAdministrateur() {
        return this.administrateur;
    }
    
    public void setAdministrateur(Administrateur administrateur) {
        this.administrateur = administrateur;
    }
    public Secretaire getSecretaire() {
        return this.secretaire;
    }
    
    public void setSecretaire(Secretaire secretaire) {
        this.secretaire = secretaire;
    }
    public Comptable getComptable() {
        return this.comptable;
    }
    
    public void setComptable(Comptable comptable) {
        this.comptable = comptable;
    }
    public Enseignant getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }

    public String getLieudenaissance() {
        return lieudenaissance;
    }

    public void setLieudenaissance(String lieudenaissance) {
        this.lieudenaissance = lieudenaissance;
    }

    public String getNationalite() {
        return nationalite;
    }

    public void setNationalite(String nationalite) {
        this.nationalite = nationalite;
    }




}


